### ISSUE TITLE
Would like to retrieve lost story

### ISSUE THREAD

**Issue by hyagreev** [Meshiest/outofcontext#9]
Hello,
Me and my friends were playing Raconteur but were not able to see the final story. Our code is t8je  If possible please retrieve all the stories written on 16 Sep 2020.

Thank you!

**Comment by Meshiest** [comment]
Hello!

Unfortunately (and fortunately) outofcontext.party does not save any data after the game ends so that story is likely unretrievable.

The only time outofcontext.party would have saved the game is if everyone left the lobby while the stories were still visible. If this was the case, you would see the stories when visiting the lobby code again.

Sorry for your loss 😢
